name: Continuous deployment

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: check-ruff
        name: Check with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'check --exit-zero --verbose'

      - id: format-ruff
        name: Format with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check --verbose'

  mypy-python:
    name: Check Python static types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'

      - name: Install Python dependencies
        run: uv sync --extra mypy

      - name: Run mypy
        run: uv run mypy ./pipeline --ignore-missing-imports
